stages:
  - pages
  - deploy

update_docs:
  stage: pages
  image: node:8.9.3
  script:
    - yarn
    - npm run analyze
    - npm run build-docs
    - mv docs public
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - docker

trigger_build:
  stage: deploy
  before_script:
    - apt-get update && apt-get install -y curl
  script:
    - "curl -X POST -F token=$CATALYST_ELEMENTS_PIPELINE_TOKEN -F ref=$CATALYST_ELEMENTS_PIPELINE_REF --insecure https://gitlab.wgtn.cat-it.co.nz/api/v4/projects/1077/trigger/pipeline"
  only:
    - tags
