stages:
  - pages
  - test

update_docs:
  stage: pages
  image: node:8.9.3
  script:
    - yarn
    - npm run analyze
    - npm run build-docs
    - mv docs public
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - docker

run_tests:
  stage: test
  image: node:8.9.3
  script:
    - yarn
    - yarn run test
  only:
    - branches
  tags:
    - docker
