stages:
  - test

run_tests:
  stage: test
  image: gitlab.wgtn.cat-it.co.nz:4567/rebeccastevens/docker-wct-image
  script:
    - yarn install
    - yarn run test
  only:
    - branches
  tags:
    - docker
